export const ProjectData = [
	{
		title: 'Domain Address Locator',
		img: '/mockups/p14-desktop.png.webp',
		img2: '/mockups/p14-mobile.png.webp',
		description:
			'A domain address tracker. Converts domain address to ip address and shows the geographic location of the ip address.',
		stack: [
			'NextJS',
			'Leaflet',
			'React-Leaflet',
			'ipify',
			'Vercel',
			'Tailwind',
			'Typescript',
		],
		links: {
			github:
				'https://github.com/Muadh-Adekunle-Monsuru/domain-address-tracker',
			vercel: 'https://domain-address-tracker.vercel.app/',
		},
	},
	{
		title: 'Chirp',
		img: '/mockups/p13-laptop.png.webp',
		img2: '/mockups/p13-mobile.png.webp',
		description: 'A text only microblogging site. Made with React',
		stack: [
			'Redux',
			'Tanstack Query',
			'NextJs',
			'MongoDB',
			'Vercel',
			'Tailwind',
			'Framer Motion',
			'Typescript',
		],
		links: {
			github: 'https://github.com/Muadh-Adekunle-Monsuru/chirp',
			vercel: 'https://chirp-posts.vercel.app/',
		},
	},
	{
		title: 'Employee Management Dashboard',
		img: '/mockups/p1-laptop.png.webp',
		img2: '/mockups/p1-phone.png.webp',
		description: 'An employee management dashboard for Appollonia Dentals',
		stack: [
			'NextJs',
			'MongoDB',
			'Vercel',
			'Tailwind',
			'Appwrite',
			'Framer',
			'Typescript',
		],
		links: {
			github: 'https://github.com/Muadh-Adekunle-Monsuru/empolyee-management',
			vercel: 'https://empolyee-management.vercel.app/',
		},
	},
	{
		title: 'Cinema Seat Reservation',
		img: '/mockups/p2-laptop.png.webp',
		img2: '/mockups/p2-phone.png.webp',
		description: 'Online seat reservation for The Cinema',
		stack: [
			'Vite',
			'React',
			'MongoDB',
			'Vercel',
			'Tailwind',
			'EmailJS',
			'Typescript',
		],
		links: {
			github: 'https://github.com/Muadh-Adekunle-Monsuru/reservations',
			vercel: 'https://reservations-two.vercel.app/',
		},
	},
	{
		title: 'Weather App',
		img: '/mockups/p3-laptop.png.webp',
		img2: '/mockups/p3-mobile.png.webp',
		description: 'Weather Forecast Checker for major European cities',
		stack: [
			'Vite',
			'React',
			'OpenWeaterMap',
			'Vercel',
			'Tailwind',
			'Typescript',
		],
		links: {
			github: 'https://github.com/Muadh-Adekunle-Monsuru/weather',
			vercel: 'https://weather-beryl-mu.vercel.app/',
		},
	},
	{
		title: 'Multi-Form Game Booking Page',
		img: '/mockups/p10-laptop.png.webp',
		img2: '/mockups/p10-mobile.png.webp',
		description: 'A multi-paged form for booking a gaming service.',
		stack: ['Redux', 'Vite', 'Vercel', 'Tailwind', 'EmailJs', 'Typescript'],
		links: {
			github: 'https://github.com/Muadh-Adekunle-Monsuru/multi-form-login',
			vercel: 'https://love-gaming-form.vercel.app/',
		},
	},
	{
		title: 'Game Booking Dashboard',
		img: '/mockups/p12-laptop.png.webp',
		img2: '/mockups/p10mobile.png.webp',
		description: 'Dashboard for viewing and dispatching all game booking made.',
		stack: [
			'Redux',
			'Tanstack Query',
			'Vite',
			'Vercel',
			'Tailwind',
			'Typescript',
			'AG-Grid',
		],
		links: {
			github: 'https://github.com/Muadh-Adekunle-Monsuru/Love-Gaming-Dashboard',
			vercel: 'https://love-gaming-dashboard.vercel.app/',
		},
	},
	{
		title: 'Crypt.Me',
		img: '/mockups/p4-laptop.png.webp',
		img2: '/mockups/p4-mobile.png.webp',
		description: 'Crypto app landing page.',
		stack: ['Vite', 'React', 'Vercel', 'Tailwind'],
		links: {
			github: 'https://github.com/Muadh-Adekunle-Monsuru/crypt.me',
			vercel: 'https://crypt-me.vercel.app/',
		},
	},
	{
		title: 'Rock Paper Scissors Game',
		img: '/mockups/p11-laptop.png.webp',
		img2: '/mockups/p11-mobile.png.webp',
		description:
			'Beautifly crafted game of Rock, Paper, Sciccors. With a bonus rendition from Big Bang Theory.',
		stack: [
			'Redux',
			'Framer Motion',
			'Vite',
			'React',
			'Vercel',
			'Tailwind',
			'Typescript',
		],
		links: {
			github: 'https://github.com/Muadh-Adekunle-Monsuru/rock-paper-scissors',
			vercel: 'https://little-rock.vercel.app/',
		},
	},
	{
		title: 'Flights Into Lagos',
		img: '/mockups/rn3.png.webp',
		img2: '/mockups/rn4.png.webp',
		description:
			'An android application that lists flights inbound into Murital Muhammad International Airport and updates hourly from realtime airtime data.',
		stack: ['React Native', 'Expo', 'Expo SqlLite', 'OpenSky API', 'twrnc'],
		links: {
			github: 'https://github.com/Muadh-Adekunle-Monsuru/flights',
			vercel: 'https://github.com/Muadh-Adekunle-Monsuru/flights',
		},
	},
	{
		title: 'Where in the world?',
		img: '/mockups/p5-laptop.png.webp',
		img2: '/mockups/p5-mobile.png.webp',
		description: 'Mini encyclopedia for every country.',
		stack: ['Vite', 'React', 'Vercel', 'Tailwind', 'Supabase'],
		links: {
			github: 'https://github.com/Muadh-Adekunle-Monsuru/countries',
			vercel: 'https://countries-kjoa.vercel.app/',
		},
	},
	{
		title: 'Hub QRCode Checker',
		img: '/mockups/p6-laptop.png.webp',
		img2: '/mockups/p6-mobile.png.webp',
		description:
			'Prototype dashboard to check students details using QR Code attached to the ID.',
		stack: ['Vite', 'React', 'Vercel', 'Tailwind', 'Supabase'],
		links: {
			github: 'https://github.com/Muadh-Adekunle-Monsuru/qrcode',
			vercel: 'https://qrcode-steel.vercel.app/',
		},
	},
	{
		title: 'Former Portfolio Page',
		img: '/mockups/p7-laptop.png.webp',
		img2: '/mockups/p7-mobile.png.webp',
		description: 'My former portfolio page which showcases older web projects.',
		stack: ['Hugo', 'Netlify', 'Bootstrap'],
		links: {
			github: 'https://github.com/Muadh-Adekunle-Monsuru/',
			vercel: 'https://muadhportfolio.netlify.app/',
		},
	},
	{
		title: 'My Landing Page',
		img: '/mockups/p8-laptop.png.webp',
		img2: '/mockups/p8-mobile.png.webp',
		description: 'My landing page.',
		stack: ['Carrd.io'],
		links: {
			github: 'https://github.com/Muadh-Adekunle-Monsuru/',
			vercel: 'https://muadhmonsur.carrd.co/',
		},
	},
	{
		title: 'LingoQL',
		img: '/mockups/p9-laptop.png.webp',
		img2: '/mockups/p9-mobile.png.webp',
		description: 'Revolutionize your query experience.',
		stack: ['Vite', 'React', 'Appwrite'],
		links: {
			github: 'https://github.com/Klusterthon-Group-105/lingoQL-frontend',
			vercel: 'https://lingoql.onrender.com/',
		},
	},
	{
		title: 'Dictionary',
		img: '/mockups/rn1.png.webp',
		img2: '/mockups/rn2.png.webp',
		description: 'An android dictionary and synonyms application.',
		stack: ['React Native', 'Expo', 'Axios'],
		links: {
			github: 'https://github.com/Muadh-Adekunle-Monsuru/words-app',
			vercel: 'https://github.com/Muadh-Adekunle-Monsuru/words-app',
		},
	},
];
