export const ProjectData = [
	{
		title: 'Sennep',
		img: '/mockups/p22-laptop.png.webp',
		img2: '/mockups/p22-mobile.png.webp',
		description: 'Using Rive React to create animations on a landing page.',
		stack: ['Vite', 'Rive', 'Framer Motion', 'Tailwind'],
		links: {
			github: 'https://github.com/Muadh-Adekunle-Monsuru/sennep',
			vercel: 'https://sennep.vercel.app/',
		},
	},
	{
		title: 'Issue Tracker',
		img: '/mockups/p21-laptop.png.webp',
		img2: '/mockups/p21-mobile.png.webp',
		description:
			'View, Create, Update, and Edit Issues. View issue summary with insightful charts.',
		stack: [
			'NextJS',
			'Prisma',
			'MongoDb',
			'Auth0',
			'Sentry',
			'Zod',
			'Convex',
			'React Markdown',
			'Recharts',
		],
		links: {
			github: 'https://github.com/Muadh-Adekunle-Monsuru/issueTracker',
			vercel: 'https://issue-tracker-beta-blue.vercel.app/',
		},
	},
	{
		title: 'Horizon Banking',
		img: '/mockups/p20-laptop.png.webp',
		img2: '/mockups/p20-mobile.png.webp',
		description:
			'Manage your finacials with Horizon. Make tranasctions, create accounts and view income.',
		stack: [
			'NextJS',
			'Prisma',
			'MongoDb',
			'PDF-Lib',
			'Sentry',
			'Zod',
			'Typescript',
		],
		links: {
			github: 'https://github.com/Muadh-Adekunle-Monsuru/horizon-banking',
			vercel: 'https://horizon-banking-app-olive.vercel.app/',
		},
	},
	{
		title: 'Déplacé Maison',
		img: '/mockups/p19-laptop.png.webp',
		img2: '/mockups/p19-mobile.png.webp',
		description:
			'Replication of Déplacé Maison, Learning to create visually captivating landing pages',
		stack: [
			'Vite',
			'React',
			'Swiper',
			'React-intersection-observer',
			'Framer Motion',
			'Typescript',
		],
		links: {
			github: 'https://github.com/Muadh-Adekunle-Monsuru/deplace-maison',
			vercel: 'https://deplace-maison.vercel.app/',
		},
	},
	{
		title: 'Account Statement Visualizer',
		img: '/mockups/p18-laptop.png.webp',
		img2: '/mockups/p18-mobile.png.webp',
		description:
			'An application to analyize your account statments with beautiful graphs.',
		stack: [
			'Vite',
			'React',
			'Google Gemmini',
			'Shadcn-Ui',
			'PdfReader',
			'Recharts',
			'Tailwind',
			'Typescript',
		],
		links: {
			github:
				'https://github.com/Muadh-Adekunle-Monsuru/AccountStatementVisualizer',
			vercel: 'https://account-statement-visualizer.vercel.app/',
		},
	},
	{
		title: 'Basic Dept',
		img: '/mockups/p17-laptop.png.webp',
		img2: '/mockups/p17-mobile.png.webp',
		description: 'An interactive landing page.',
		stack: [
			'Vite',
			'React',
			'React Video Player',
			'Framer Motion',
			'React Swiper',
			'Intersection Observer',
			'Tailwind',
			'Typescript',
		],
		links: {
			github: 'https://github.com/Muadh-Adekunle-Monsuru/Basic-Dept',
			vercel: 'https://basic-dept-mu.vercel.app/',
		},
	},
	{
		title: 'Jotion',
		img: '/mockups/p16-laptop.png.webp',
		img2: '/mockups/p16-mobile.png.webp',
		description: 'A minimalist note taking app, inspired by Notion.',
		stack: [
			'NextJS',
			'Zustand',
			'Convex',
			'Clerk',
			'Vercel',
			'Shadcn-Ui',
			'Blocknote',
			'Sonner',
			'Tailwind',
			'Typescript',
		],
		links: {
			github: 'https://github.com/Muadh-Adekunle-Monsuru/my-notion',
			vercel: 'https://just-jotion.vercel.app/',
		},
	},
	{
		title: 'Marcado Casa',
		img: '/mockups/p15-laptop.png.webp',
		img2: '/mockups/p15-mobile.png.webp',
		description:
			'An ecommerce site to find your ideal apartment effortlessly with curated listings and simple booking. Sell items hassle-free in our marketplace, connecting with eager buyers. ',
		stack: [
			'NextJS',
			'Redux',
			'Ag-Grid',
			'Cloudinary',
			'Vercel',
			'EmailJs',
			'React Swiper',
			'AOS',
			'Framer',
			'Tailwind',
			'Typescript',
		],
		links: {
			github:
				'https://github.com/Muadh-Adekunle-Monsuru/mercado/tree/main/mercado-user',
			vercel: 'https://marcadocasa.ng/',
		},
	},
	{
		title: 'Domain Address Locator',
		img: '/mockups/p14-desktop.png.webp',
		img2: '/mockups/p14-mobile.png.webp',
		description:
			'A domain address tracker. Converts domain address to ip address and shows the geographic location of the ip address.',
		stack: [
			'NextJS',
			'Leaflet',
			'React-Leaflet',
			'ipify',
			'Vercel',
			'Tailwind',
			'Typescript',
		],
		links: {
			github:
				'https://github.com/Muadh-Adekunle-Monsuru/domain-address-tracker',
			vercel: 'https://domain-address-tracker.vercel.app/',
		},
	},
	{
		title: 'Chirp',
		img: '/mockups/p13-laptop.png.webp',
		img2: '/mockups/p13-mobile.png.webp',
		description: 'A text only microblogging site. Made with React',
		stack: [
			'Redux',
			'Tanstack Query',
			'NextJs',
			'MongoDB',
			'Vercel',
			'Tailwind',
			'Framer Motion',
			'Typescript',
		],
		links: {
			github: 'https://github.com/Muadh-Adekunle-Monsuru/chirp',
			vercel: 'https://chirp-posts.vercel.app/',
		},
	},
	{
		title: 'Employee Management Dashboard',
		img: '/mockups/p1-laptop.png.webp',
		img2: '/mockups/p1-phone.png.webp',
		description: 'An employee management dashboard for Appollonia Dentals',
		stack: [
			'NextJs',
			'MongoDB',
			'Vercel',
			'Tailwind',
			'Appwrite',
			'Framer',
			'Typescript',
		],
		links: {
			github: 'https://github.com/Muadh-Adekunle-Monsuru/empolyee-management',
			vercel: 'https://empolyee-management.vercel.app/',
		},
	},
	{
		title: 'Cinema Seat Reservation',
		img: '/mockups/p2-laptop.png.webp',
		img2: '/mockups/p2-phone.png.webp',
		description: 'Online seat reservation for The Cinema',
		stack: [
			'Vite',
			'React',
			'MongoDB',
			'Vercel',
			'Tailwind',
			'EmailJS',
			'Typescript',
		],
		links: {
			github: 'https://github.com/Muadh-Adekunle-Monsuru/reservations',
			vercel: 'https://reservations-two.vercel.app/',
		},
	},
	{
		title: 'Weather App',
		img: '/mockups/p3-laptop.png.webp',
		img2: '/mockups/p3-mobile.png.webp',
		description: 'Weather Forecast Checker for major European cities',
		stack: [
			'Vite',
			'React',
			'OpenWeaterMap',
			'Vercel',
			'Tailwind',
			'Typescript',
		],
		links: {
			github: 'https://github.com/Muadh-Adekunle-Monsuru/weather',
			vercel: 'https://weather-beryl-mu.vercel.app/',
		},
	},
	{
		title: 'Multi-Form Game Booking Page',
		img: '/mockups/p10-laptop.png.webp',
		img2: '/mockups/p10-mobile.png.webp',
		description: 'A multi-paged form for booking a gaming service.',
		stack: ['Redux', 'Vite', 'Vercel', 'Tailwind', 'EmailJs', 'Typescript'],
		links: {
			github: 'https://github.com/Muadh-Adekunle-Monsuru/multi-form-login',
			vercel: 'https://love-gaming-form.vercel.app/',
		},
	},
	{
		title: 'Game Booking Dashboard',
		img: '/mockups/p12-laptop.png.webp',
		img2: '/mockups/p10mobile.png.webp',
		description: 'Dashboard for viewing and dispatching all game booking made.',
		stack: [
			'Redux',
			'Tanstack Query',
			'Vite',
			'Vercel',
			'Tailwind',
			'Typescript',
			'AG-Grid',
		],
		links: {
			github: 'https://github.com/Muadh-Adekunle-Monsuru/Love-Gaming-Dashboard',
			vercel: 'https://love-gaming-dashboard.vercel.app/',
		},
	},
	{
		title: 'Crypt.Me',
		img: '/mockups/p4-laptop.png.webp',
		img2: '/mockups/p4-mobile.png.webp',
		description: 'Crypto app landing page.',
		stack: ['Vite', 'React', 'Vercel', 'Tailwind'],
		links: {
			github: 'https://github.com/Muadh-Adekunle-Monsuru/crypt.me',
			vercel: 'https://crypt-me.vercel.app/',
		},
	},
	{
		title: 'Rock Paper Scissors Game',
		img: '/mockups/p11-laptop.png.webp',
		img2: '/mockups/p11-mobile.png.webp',
		description:
			'Beautifly crafted game of Rock, Paper, Sciccors. With a bonus rendition from Big Bang Theory.',
		stack: [
			'Redux',
			'Framer Motion',
			'Vite',
			'React',
			'Vercel',
			'Tailwind',
			'Typescript',
		],
		links: {
			github: 'https://github.com/Muadh-Adekunle-Monsuru/rock-paper-scissors',
			vercel: 'https://little-rock.vercel.app/',
		},
	},
	{
		title: 'Flights Into Lagos',
		img: '/mockups/rn3.png.webp',
		img2: '/mockups/rn4.png.webp',
		description:
			'An android application that lists flights inbound into Murital Muhammad International Airport and updates hourly from realtime airtime data.',
		stack: ['React Native', 'Expo', 'Expo SqlLite', 'OpenSky API', 'twrnc'],
		links: {
			github: 'https://github.com/Muadh-Adekunle-Monsuru/flights',
			vercel: 'https://github.com/Muadh-Adekunle-Monsuru/flights',
		},
	},
	{
		title: 'Where in the world?',
		img: '/mockups/p5-laptop.png.webp',
		img2: '/mockups/p5-mobile.png.webp',
		description: 'Mini encyclopedia for every country.',
		stack: ['Vite', 'React', 'Vercel', 'Tailwind', 'Supabase'],
		links: {
			github: 'https://github.com/Muadh-Adekunle-Monsuru/countries',
			vercel: 'https://countries-kjoa.vercel.app/',
		},
	},
	{
		title: 'Hub QRCode Checker',
		img: '/mockups/p6-laptop.png.webp',
		img2: '/mockups/p6-mobile.png.webp',
		description:
			'Prototype dashboard to check students details using QR Code attached to the ID.',
		stack: ['Vite', 'React', 'Vercel', 'Tailwind', 'Supabase'],
		links: {
			github: 'https://github.com/Muadh-Adekunle-Monsuru/qrcode',
			vercel: 'https://qrcode-steel.vercel.app/',
		},
	},
	{
		title: 'Former Portfolio Page',
		img: '/mockups/p7-laptop.png.webp',
		img2: '/mockups/p7-mobile.png.webp',
		description: 'My former portfolio page which showcases older web projects.',
		stack: ['Hugo', 'Netlify', 'Bootstrap'],
		links: {
			github: 'https://github.com/Muadh-Adekunle-Monsuru/',
			vercel: 'https://muadhportfolio.netlify.app/',
		},
	},
	{
		title: 'My Landing Page',
		img: '/mockups/p8-laptop.png.webp',
		img2: '/mockups/p8-mobile.png.webp',
		description: 'My landing page.',
		stack: ['Carrd.io'],
		links: {
			github: 'https://github.com/Muadh-Adekunle-Monsuru/',
			vercel: 'https://muadhmonsur.carrd.co/',
		},
	},
	{
		title: 'LingoQL',
		img: '/mockups/p9-laptop.png.webp',
		img2: '/mockups/p9-mobile.png.webp',
		description: 'Revolutionize your query experience.',
		stack: ['Vite', 'React', 'Appwrite'],
		links: {
			github: 'https://github.com/Klusterthon-Group-105/lingoQL-frontend',
			vercel: 'https://lingoql.onrender.com/',
		},
	},
	{
		title: 'Dictionary',
		img: '/mockups/rn1.png.webp',
		img2: '/mockups/rn2.png.webp',
		description: 'An android dictionary and synonyms application.',
		stack: ['React Native', 'Expo', 'Axios'],
		links: {
			github: 'https://github.com/Muadh-Adekunle-Monsuru/words-app',
			vercel: 'https://github.com/Muadh-Adekunle-Monsuru/words-app',
		},
	},
];
